#include "export.hpp"

#include <spdlog/spdlog.h>

#include <chrono>
#include <fstream>
#include <nlohmann/json.hpp>
#include <string>

#include "common.hpp"
#include "models.hpp"
#include "provider_base.hpp"

using namespace wslam;
using nlohmann::json;

#define LOG_ID "[Export]"

namespace {

constexpr int kFormatVersion = 1;

// Returns the JSON sidecar path derived from a .ply map path by replacing the
// extension. Errors out if the input does not look like a `.ply` file so the
// pairing stays predictable for the Python viewer.
std::optional<std::filesystem::path> deriveMetadataPath(
    const std::filesystem::path& map_path) {
    if (map_path.empty()) {
        return std::nullopt;
    }
    std::filesystem::path out = map_path;
    out.replace_extension(".json");
    return out;
}

// ASCII PLY writer kept inline because the format is tiny and pulling a
// dependency for ~20 lines of header + per-vertex floats would be overkill.
// The `landmark_id` property survives loading by anything that respects PLY
// custom properties (plyfile, Open3D, meshlab).
std::optional<std::string> writePly(
    const std::filesystem::path& path,
    const std::vector<LandmarkEstimate>& landmarks) {
    std::ofstream f(path);
    if (!f) {
        return std::format("could not open '{}' for writing", path.string());
    }

    f << "ply\n"
      << "format ascii 1.0\n"
      << "comment generated by pc_wslam export\n"
      << "element vertex " << landmarks.size() << "\n"
      << "property float x\n"
      << "property float y\n"
      << "property float z\n"
      << "property uint landmark_id\n"
      << "end_header\n";

    for (const auto& lm : landmarks) {
        f << static_cast<float>(lm.position_world.x()) << ' '
          << static_cast<float>(lm.position_world.y()) << ' '
          << static_cast<float>(lm.position_world.z()) << ' '
          << lm.id.v << '\n';
    }

    if (!f) {
        return std::format("write error on '{}'", path.string());
    }
    return std::nullopt;
}

json poseToJson(const KeyframePose& kf) {
    json r = json::array();
    for (Eigen::Index row = 0; row < 3; ++row) {
        json row_arr = json::array();
        for (Eigen::Index col = 0; col < 3; ++col) {
            row_arr.push_back(kf.R_world_cam(row, col));
        }
        r.push_back(std::move(row_arr));
    }
    return json{
        {"id", kf.id.v},
        {"R_world_cam", r},
        {"t_world_cam",
         json::array({kf.t_world_cam.x(), kf.t_world_cam.y(),
                      kf.t_world_cam.z()})},
    };
}

json cameraToJson(const data::CamSensorParams& cam) {
    return json{
        {"fx", cam.intrinsics(0)},        {"fy", cam.intrinsics(1)},
        {"cx", cam.intrinsics(2)},        {"cy", cam.intrinsics(3)},
        {"k1", cam.distortion_coefficients(0)},
        {"k2", cam.distortion_coefficients(1)},
        {"p1", cam.distortion_coefficients(2)},
        {"p2", cam.distortion_coefficients(3)},
        {"width", cam.resolution.at(0)},  {"height", cam.resolution.at(1)},
        {"model", cam.camera_model},      {"distortion_model", cam.distortion_model},
    };
}

std::optional<std::string> writeJson(const std::filesystem::path& path,
                                     const MapSnapshot& snap,
                                     const data::CamSensorParams& cam) {
    json doc;
    doc["format_version"] = kFormatVersion;
    // OpenCV convention: x-right, y-down, z-forward (along view direction).
    // Documented so the viewer can configure its scene axes consistently.
    doc["coordinate_system"] = "RDF";
    doc["camera"] = cameraToJson(cam);

    json keyframes = json::array();
    keyframes.get_ref<json::array_t&>().reserve(snap.keyframes.size());
    for (const auto& kf : snap.keyframes) {
        keyframes.push_back(poseToJson(kf));
    }
    doc["keyframes"] = std::move(keyframes);

    json ids = json::array();
    ids.get_ref<json::array_t&>().reserve(snap.landmarks.size());
    for (const auto& lm : snap.landmarks) {
        ids.push_back(lm.id.v);
    }
    doc["landmark_ids"] = std::move(ids);

    doc["stats"] = json{
        {"keyframes", snap.stats.keyframes},
        {"landmarks", snap.stats.landmarks},
        {"factors", snap.stats.factors},
    };

    doc["created_at_unix"]
        = std::chrono::duration_cast<std::chrono::seconds>(
              std::chrono::system_clock::now().time_since_epoch())
              .count();

    std::ofstream f(path);
    if (!f) {
        return std::format("could not open '{}' for writing", path.string());
    }
    constexpr int kIndent = 2;
    f << doc.dump(kIndent) << '\n';
    if (!f) {
        return std::format("write error on '{}'", path.string());
    }
    return std::nullopt;
}

}  // namespace

std::optional<std::string> wslam::ExportMap(const AnyBag& storage,
                                            const ExportOpts& opts) {
    spdlog::info(LOG_ID " Exporting map to '{}'", opts.map_path.string());

    if (opts.map_path.empty()) {
        return "ExportMap: map_path is empty";
    }
    if (opts.map_path.extension() != ".ply") {
        return std::format(
            "ExportMap: map_path must end in '.ply' (got '{}')",
            opts.map_path.extension().string());
    }

    const auto meta_path_opt = deriveMetadataPath(opts.map_path);
    if (!meta_path_opt.has_value()) {
        return "ExportMap: failed to derive JSON sidecar path";
    }
    const auto& meta_path = meta_path_opt.value();

    const auto snap_ptr
        = storage.getPtr<MapSnapshot>(ResourceIdentifier::MapSnapshotName);
    if (!snap_ptr.has_value()) {
        return std::format("ExportMap: no MapSnapshot under key '{}'",
                           ResourceIdentifier::MapSnapshotName);
    }
    const auto& snap = *snap_ptr.value();

    const auto cam_key
        = ResourceIdentifier::GetCameraIntrinsicsName(opts.camera_index);
    const auto cam_ptr = storage.getPtr<data::CamSensorParams>(cam_key);
    if (!cam_ptr.has_value()) {
        return std::format("ExportMap: no CamSensorParams under key '{}'",
                           cam_key);
    }
    const auto& cam = *cam_ptr.value();

    // Make sure the output directory exists; create it if asked for a fresh
    // path. Caller-provided directories that *should* already exist (e.g. a
    // shared output volume) are unaffected because create_directories is a
    // no-op when the path is already present.
    if (opts.map_path.has_parent_path()) {
        std::error_code ec;
        std::filesystem::create_directories(opts.map_path.parent_path(), ec);
        if (ec) {
            return std::format("ExportMap: cannot create output dir '{}': {}",
                               opts.map_path.parent_path().string(),
                               ec.message());
        }
    }

    if (auto err = writePly(opts.map_path, snap.landmarks)) {
        return std::format("writing PLY: {}", err.value());
    }
    if (auto err = writeJson(meta_path, snap, cam)) {
        return std::format("writing JSON metadata: {}", err.value());
    }

    spdlog::info(LOG_ID
                 " Wrote map: {} landmarks → '{}', {} keyframes → '{}'",
                 snap.landmarks.size(), opts.map_path.string(),
                 snap.keyframes.size(), meta_path.string());

    return std::nullopt;
}
